# Generated by Django 5.2.3 on 2025-06-20 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.CharField(max_length=500)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('llm', 'LLM Automatique'), ('expert', 'Expert Humain'), ('rule', 'Règle Métier')], default='llm', max_length=10)),
                ('validation_status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('modified', 'Modifié')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotations', to=settings.AUTH_USER_MODEL)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regulatoryentity')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.documentsentence')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
                'ordering': ['sentence', 'start_position'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_model', models.CharField(default='mistral-7b-instruct', max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='running', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
            options={
                'verbose_name': "Session d'annotation",
                'verbose_name_plural': "Sessions d'annotation",
            },
        ),
        migrations.CreateModel(
            name='ExpertFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('correction', 'Correction'), ('suggestion', 'Suggestion'), ('validation', 'Validation')], max_length=20)),
                ('comment', models.TextField()),
                ('suggested_value', models.CharField(blank=True, max_length=500)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='annotations.annotation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Expert',
                'verbose_name_plural': 'Feedbacks Experts',
            },
        ),
    ]
