# Generated by Django 5.2.3 on 2025-06-22 09:12

import apps.documents.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auto_extracted_country',
            field=models.CharField(blank=True, help_text='Pays extrait automatiquement', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='auto_extracted_date',
            field=models.DateField(blank=True, help_text='Date extraite automatiquement', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='auto_extracted_language',
            field=models.CharField(blank=True, help_text='Langue détectée automatiquement', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='auto_extracted_source',
            field=models.CharField(blank=True, help_text='Source extraite automatiquement', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='auto_extracted_title',
            field=models.CharField(blank=True, help_text='Titre extrait automatiquement', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='auto_extracted_version',
            field=models.CharField(blank=True, help_text='Version extraite automatiquement', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='date_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_confidence',
            field=models.JSONField(blank=True, default=dict, help_text='Scores de confiance pour chaque métadonnée'),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_patterns_used',
            field=models.JSONField(blank=True, default=list, help_text="Patterns utilisés pour l'extraction"),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='language_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='source_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='title_manually_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsentence',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Score de confiance pour le type détecté'),
        ),
        migrations.AddField(
            model_name='documentsentence',
            name='end_position',
            field=models.IntegerField(blank=True, help_text='Position de fin dans le texte', null=True),
        ),
        migrations.AddField(
            model_name='documentsentence',
            name='sentence_type',
            field=models.CharField(blank=True, help_text='Type de phrase détecté', max_length=50),
        ),
        migrations.AddField(
            model_name='documentsentence',
            name='start_position',
            field=models.IntegerField(blank=True, help_text='Position de début dans le texte', null=True),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='domain_patterns',
            field=models.TextField(blank=True, help_text='Domaines séparés par des virgules'),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='name_patterns',
            field=models.TextField(blank=True, help_text='Patterns de reconnaissance séparés par des virgules'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('guideline', 'Guideline'), ('procedure', 'Procédure'), ('variation', 'Variation'), ('regulation', 'Règlement'), ('directive', 'Directive'), ('circular', 'Circulaire'), ('notice', 'Notice'), ('report', 'Rapport'), ('autres', 'Autres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'html', 'htm', 'rtf', 'odt'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('de', 'Allemand'), ('es', 'Espagnol'), ('it', 'Italien'), ('pt', 'Portugais'), ('nl', 'Néerlandais'), ('auto', 'Détection automatique')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Téléchargé'), ('processing', 'En cours de traitement'), ('metadata_extracted', 'Métadonnées extraites'), ('annotated', 'Annoté'), ('validated', 'Validé'), ('error', 'Erreur')], default='uploaded', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraping_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(blank=True, help_text='URL source si applicable')),
                ('file_type', models.CharField(max_length=50)),
                ('context', models.CharField(choices=[('pharma', 'Pharmaceutique'), ('juridique', 'Juridique'), ('gouvernement', 'Gouvernement'), ('medical', 'Médical'), ('research', 'Recherche'), ('autre', 'Autre')], default='pharma', max_length=20)),
                ('extracted_title', models.CharField(blank=True, max_length=500)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('extracted_language', models.CharField(blank=True, max_length=10)),
                ('extracted_country', models.CharField(blank=True, max_length=100)),
                ('extracted_source', models.CharField(blank=True, max_length=100)),
                ('extracted_version', models.CharField(blank=True, max_length=50)),
                ('confidence_title', models.IntegerField(default=0)),
                ('confidence_date', models.IntegerField(default=0)),
                ('confidence_language', models.IntegerField(default=0)),
                ('confidence_source', models.IntegerField(default=0)),
                ('extraction_status', models.CharField(choices=[('success', 'Succès'), ('partial', 'Partiel'), ('failed', 'Échec')], default='success', max_length=20)),
                ('extraction_notes', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Temps en secondes', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_logs', to='documents.document')),
            ],
            options={
                'verbose_name': "Log d'extraction",
                'verbose_name_plural': "Logs d'extraction",
                'ordering': ['-scraping_date'],
            },
        ),
    ]
